In [3]:
import numpy as np
import pandas as pd

In [7]:
sales = pd.Series([1,2,3])
print(sales)
print(sales[1])
print(sales[0:2])

0    1
1    2
2    3
dtype: int64
2
0    1
1    2
dtype: int64

In [10]:
# ATRRIBUTES
print(sales.index)
print(sales.values)
print(sales.dtype)

RangeIndex(start=0, stop=3, step=1)
[1 2 3]
int64

In [20]:
# Methods
print(sales.head(1))
print(sales.tail(1))
print(sales.sort_values())
print(sales.count())
print(sales.notnull())

0    1
dtype: int64
2    3
dtype: int64
0    1
1    2
2    3
dtype: int64
3
0    True
1    True
2    True
dtype: bool

#### DataFrame

In [25]:
data = pd.DataFrame({
    'Name' : ['Anna', 'Kakul'],
    'Lemonades' : [2, 3]
})
s1 = pd.Series(data = [1,2,3,4,5])
s2 = pd.Series(data=[37,9,4,2,2])
#s1 = pd.Series(data = [100, 200, 300, 400, 500], index = list('abcde'))

data = pd.DataFrame({"C1":s1, 'C2': s2})
print(data)

   C1  C2
0   1  37
1   2   9
2   3   4
3   4   2
4   5   2

In [28]:
print(data.shape)
print(data.columns)

(5, 2)
Index(['C1', 'C2'], dtype='object')

#### Loc and iloc

In [35]:

print(data.loc[0]['C1'])
print(data.iloc[0,1])

1
37

In [36]:
data.describe()

             C1         C2
count  5.000000   5.000000
mean   3.000000  10.800000
std    1.581139  14.923136
min    1.000000   2.000000
25%    2.000000   2.000000
50%    3.000000   4.000000
75%    4.000000   9.000000
max    5.000000  37.000000

## Filtering

In [37]:
data[data['C1'] > 2]

   C1  C2
2   3   4
3   4   2
4   5   2

#### Adding, Updating, Deleting

In [43]:
data['c3'] = [1,2,3,4,5]

del data['c3']
data

   C1  C2
0   1  37
1   2   9
2   3   4
3   4   2
4   5   2

In [45]:
data = data.drop(columns = ['C2'])

In [46]:
data

   C1
0   1
1   2
2   3
3   4
4   5

In [49]:
data.loc[data['C1'] == 2] = 6
data

   C1
0   1
1   6
2   3
3   4
4   5

In [53]:
data.rename(columns={'C1':'Score'}, inplace = True)
data

   Score
0      1
1      6
2      3
3      4
4      5

In [55]:
data['tips'] = ['a','b','c','d','e']
data

   Score tips
0      1    a
1      6    b
2      3    c
3      4    d
4      5    e

In [62]:
data

      Score
tips
a         1
b         6
c         3
d         4
e         5

In [64]:
data.loc['a']

Score    1
Name: a, dtype: int64

In [66]:
multi_data = pd.DataFrame({
    'Park': ['A', 'A', 'B', 'B'],
    'Name': ['Anna', 'Ben', 'Chris', 'Daiary'],
    'Lemonnades': [2, 3, 4, 5]
}).set_index(['Park', 'Name'])

print(multi_data)

             Lemonnades
Park Name
A    Anna             2
     Ben              3
B    Chris            4
     Daiary           5

In [67]:
multi_data[multi_data['Lemonnades'] > 3]

             Lemonnades
Park Name
B    Chris            4
     Daiary           5

In [69]:
multi_data.query('Lemonnades > 3')

             Lemonnades
Park Name
B    Chris            4
     Daiary           5

In [70]:
multi_data.mean()

Lemonnades    3.5
dtype: float64